# 数据字典

#启动参数
ORIGIN_CAPTION = "Magic Tower"
PIXEL_GRID = 32

# 总界面screen参数
SCREEN_G_POINTX = 0
SCREEN_G_POINTY = 0
SCREEN_W_G = 20
SCREEN_H_G = 15
SCREEN_WIDTH = SCREEN_W_G * PIXEL_GRID  # 640
SCREEN_HEIGHT = SCREEN_H_G * PIXEL_GRID  # 480
SCREEN_RECT = (0, 0, SCREEN_WIDTH, SCREEN_HEIGHT)
SCREEN_SIZE = (SCREEN_WIDTH, SCREEN_HEIGHT)

# Active活动区参数
ACT_G_POINTX = 6
ACT_G_POINTY = 1
ACT_W_G = 13
ACT_H_G = 13
ACT_POINTX = ACT_G_POINTX * PIXEL_GRID
ACT_POINTY = ACT_G_POINTY * PIXEL_GRID
ACT_WIDTH = ACT_W_G * PIXEL_GRID
ACT_HEIGHT = ACT_H_G * PIXEL_GRID
ACT_RECT = (ACT_POINTX, ACT_POINTY, ACT_WIDTH, ACT_HEIGHT)

# 人物区参数
HERO_G_POINTX = 1
HERO_G_POINTY = 1
HERO_W_G = 4
HERO_H_G = 8
HERO_POINTX = HERO_G_POINTX * PIXEL_GRID
HERO_POINTY = HERO_G_POINTY * PIXEL_GRID
HERO_WIDTH = HERO_W_G * PIXEL_GRID
HERO_HEIGHT = HERO_H_G * PIXEL_GRID
HERO_RECT = (HERO_POINTX, HERO_POINTY, HERO_WIDTH, HERO_HEIGHT)

# 物品区参数
ITEM_G_POINTX = 1
ITEM_G_POINTY = 10
ITEM_W_G = 4
ITEM_H_G = 4
ITEM_POINTX = ITEM_G_POINTX * PIXEL_GRID
ITEM_POINTY = ITEM_G_POINTY * PIXEL_GRID
ITEM_WIDTH = ITEM_W_G * PIXEL_GRID
ITEM_HEIGHT = ITEM_H_G * PIXEL_GRID
ITEM_RECT = (ITEM_POINTX, ITEM_POINTY, ITEM_WIDTH, ITEM_HEIGHT)

# 地图参数
MAP_B_STONE = 0
MAP_W_STONE = 1
MAP_MAGMA = 2
MAP_UP_FLO = 3
MAP_DOWN_FLO = 4
MAP_IRON_RAIL = 5
# 40-60 为怪物区
MAP_MONS_SG = 40
# 61-80 为npc
MAP_NPC_RED = 61

# 键盘映射
KEY_UP =    1001
KEY_DOWN =  1002
KEY_LEFT =  1003
KEY_RIGHT = 1004
KEY_STOP = 1005

KEY_TOATK = 1009
KEY_GITEM = 1010
KEY_TRADE = 1011
KEY_TOOPEN = 1012